name: Docker build git and push to DockerHub

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.devcontainer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - 'contrib/**'
      - 'patches/**'
      - '.clangformat'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AUTHORS'
      - 'ChangeLog'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'
      - 'centos_autotools.sh'
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.devcontainer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - 'contrib/**'
      - 'patches/**'
      - '.clangformat'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AUTHORS'
      - 'ChangeLog'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'
      - 'centos_autotools.sh'

jobs:
  docker-git:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            aircrackng/git:latest
            aircrackng/git:${{ github.sha }}
